# The following configuration file is meant to be used only for development.
# Secret values provided here have no impact on the production environment.

version: "3.4"
services:
  alleycatapp-persistence:
    build: ./AlleycatApp.Auth
    command: --seed
    ports:
      - "8000:8080"
    environment:
      ConnectionStrings:DefaultConnection: "Server=db;Database=AlleycatAppDb;User=sa;Password=S3cretP@ssword;Encrypt=False;"
      Jwt:Audience: audience
      Jwt:Issuer: issuer
      Jwt:ExpirationTimeMinutes: 15
      Jwt:SecretKey: "11112222333344445555666677778888"
      InitialManagerUsername: manager@alleycatapp.com
      InitialManagerPassword: S3cretP@ssword
      ASPNETCORE_ENVIRONMENT: Development
    entrypoint: ["/wait-for-it.sh", "db:1433", "-t", "120", "--", "dotnet", "AlleycatApp.Auth.dll"]
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: S3cretP@ssword
      ACCEPT_EULA: "Y"
