name: Build, deploy and publish AlleyCat Auth microservice

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    name: Build and test Alleycat App authorization and persistence microservice
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Analyze code coverage
      run: |
        dotnet tool install JetBrains.dotCover.GlobalTool -g
        dotnet dotcover test --no-build --dcReportType=HTML --dcFilters='+:AlleycatApp.Auth;-:class=Program'
    - name: Upload coverage analysis as artifact
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: |
          ./dotCover.Output/
          ./dotCover.Output.html

  publish:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: bkisly32/alleycatapp-auth
      
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./AlleycatApp.Auth
          file: ./AlleycatApp.Auth/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
